### ISSUE TITLE
CSS: selectors

### ISSUE THREAD

**Issue by hon9g** [minh364/webDev#15]
# CSS Syntax Selectors
how to select elements from HTML file in CSS

- **Select all of elements that have `h1` HTML tag**
```CSS
h1 {
  color: blue;
}
```

- **Select all elements that have a `class` set to `btn--blue`**
```CSS
.btn--blue {
  color: blue;
}
```

- **Select an element that has an `id` set to  `entry-textarea`**
```CSS
#entry-textarea {
  border: 2px solid #ccc;
}
```

- **Select all `p` elements that have a `div` element as parent**
```CSS
div p {
  text-align: center;
}
```

- **Select multiple elements**
```CSS
h1, h2, p {
  color: blue;
}
```
